project:
  type: website
  output-dir: docs

website:
  title: "Learning"
  navbar:
    left:
      - href: index.qmd
        text: Búsqueda en BBDDs
      - RNAseq.qmd
      - AS_Analysis.qmd
      - Multimomic_Data_Integration.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



